name: islami
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_native_splash:
  background_image: assets/images/splash.png